# Generated by Django 5.1.1 on 2024-09-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='name',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='password',
            field=models.CharField(default='default@example.com', max_length=8),
            preserve_default=False,
        ),
    ]
