# Generated by Django 5.1.1 on 2024-09-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usuarios_name_usuarios_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='name',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
    ]
